version: "2.0"
services:
  keycloak:
    image: prasannjeet/keycloak-int-arch:latest
    container_name: keycloak
    ports:
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.ooguy.com`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8443"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.routers.keycloak.tls.certresolver=dynu"

networks:
  default:
    external:
      name: traefik_network

volumes:
  mysql-data:
    driver: local